#!/bin/sh

paplay /usr/share/sounds/freedesktop/stereo/dialog-warning.oga

if [ -n "$(pgrep gif_screener)" ];then
pkill -P $(pgrep gif_screener) && notify-send "gif_screener killed" || error "Can't kill gif_screener"
else
    "${HOME}/.script/gif_screener"
fi
