#!/usr/bin/sh

TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI0MTI2YTc4YjBkNjE0ZjBmYTViYTQxZmU3MGQ3MzAzMSIsImlhdCI6MTY0MTUwMTY2OSwiZXhwIjoxOTU2ODYxNjY5fQ.9-kwmmdhKAsq_5sal95LVPFkkAKVnCuhHG1EhfrZKs0"


url="http://zenocloud:8123"


curly(){
    curl -X POST -H "Authorization: Bearer $TOKEN" \
        -H "Content-Type: application/json" \
        "$url/api/services/script/$1"
#        -d "{\"entity_id\": \"light.gu10_test\"}" \
}


curly $1



