#!/bin/sh

# todo : make it work with nmcli | head -n 1

if grep -q "#.*zenocyne.com" /etc/hosts; then
	echo Intralink enabled
	sed -i 's/#\(.*zenocyne.com\)/\1/' /etc/hosts
else
	echo Intralink disabled
	sed -i 's/\(.*zenocyne.com\)/#\1/' /etc/hosts
fi
