#!/bin/sh

mpc -q pause
if find "/home/sam/Music/" | grep -q "$@"
then
    echo "$@" | sed 's|.*Music/||' | mpc -q insert
    mpc -q play
    mpc -q next
else
    nohup mpv --player-operation-mode=pseudo-gui "$@" &
fi
