#!/bin/sh

# colors from wpgtk/pywal
. "${HOME}/.cache/wal/colors.sh"

dmenucmd="dmenu -nb $color0 -nf $color15 -sb $color0 -sf $color3"
notifycmd="dunstify -i owl"

xrandrout=$(xrandr)
active=$(xrandr --listactivemonitors | grep -v "Monitors: " | awk '{print $4}')

abort () {
    [ -n "$1" ] && echo "Error: $1"
    echo "Aborted!"
    $notifycmd "Error: $1"
    exit 1
}

resetscreen () {
    "${HOME}"/.fehbg
    "${HOME}"/.config/polybar/launch.sh
}

turn_on_devices () {
    con_off_devices=$(echo "$xrandrout" | grep " connected" | grep -v "$active" | awk '{print $1}')
    numline=$(echo "$con_off_devices" | wc -l)

    if [ "$numline" = 0 ]; then
        echo "No output devices"
        $notifycmd "No output devices"
    elif [ "$numline" -gt 1 ];then
        chosenone=$(echo "$con_off_devices" | $dmenucmd -p "Choose which devices to enable: ")
    else
        chosenone="$con_off_devices"
    fi

    if [ -n "$chosenone" ];then
        leftorright=$(echo -e "left\nright" | $dmenucmd -p "Left or Right of $active?")
        if [ "$leftorright" == "right" ];then
            xrandr --output "$chosenone" --auto --right-of "$active"
        elif [ "$leftorright" == "left" ];then
            xrandr --output "$chosenone" --auto --left-of "$active"
        else
            abort "choose leftorright"
        fi
        resetscreen
    else
        echo "no devices to turn on"
        $notifycmd "no devices to turn on"
    fi
}

turn_off_devices () {
    numline=$(echo "$active" | wc -l)
    if [ "$numline" = 0 ]; then
        echo "No output devices"
        $notifycmd "No output devices"
    elif [ "$numline" -gt 1 ];then
        chosenone=$(echo "$active" | $dmenucmd -p "Choose which devices to turn off: ")
    else
        abort "Don't turn off your only monitor, silly"
    fi

    if [ -n "$chosenone" ];then
        xrandr --output "$chosenone" --off
        resetscreen
    else
        echo "no devices to turn off"
        $notifycmd "no devices to turn off"
    fi
}

menu=$(printf "enable\ndisable" | $dmenucmd -i -l 2 -p "Xrandr Script: " ) || abort

case $menu in
    enable)
        turn_on_devices ;;
    disable)
        turn_off_devices ;;
    *)
        echo "need enable or disable options"
        $notifycmd "need enable or disable options"
esac
