#!/bin/sh

. "${HOME}/.config/wpg/formats/colors.sh"

file=${HOME}/.surf/bookmarks

url=$(xprop -id "$1" | grep URI | awk '{print $3}' | sed 's/\"//g')
title=$(xprop -id "$1" | grep WM_ICON_NAME\(STRING\) | cut -c 40- | sed 's/.$//g')
echo "$url" "$title" | dmenu -nb "$color0" -nf "$color15" -sb "$color0" -sf "$color3" -p 'Add Bookmark' -w "$1" >> "$file"
