#!/bin/sh

WALLPAPERS="${HOME}/Images/wallpapers"

random_file=$(ls $WALLPAPERS | shuf | head -n1)

swww img --transition-fps 50 --transition-type fade --transition-step 10 --transition-duration 1 "${HOME}/Images/wallpapers/$random_file"
