#!/bin/sh

prount(){
    number=$(pacman -Qu | wc -l)
    [ -f "${HOME}/.cache/auwlr/auwlr_upgrade_list" ] && AUR=$(wc -l <"${HOME}/.cache/auwlr/auwlr_upgrade_list")
    [ -n "$AUR" -a ! "$AUR" = 0 ] && AUR="(+$AUR)"
    [ ! "$number" = 0 ] && echo  "$number$AUR" || echo
}

update(){
    sudo pacman -Syu
    notify-send 'Update finished successfully!'
    prount
}

case $1 in
    --update)
	update
	;;
    *)
	prount
	;;
esac
