#!/bin/sh

cable=$(cat /sys/class/net/enp3s0/operstate)

inversebool () {
    [[ "$1" = 0 ]] && echo 1 || echo 0
}

getifstat () {
    ifstat -n
    if [[ -n $(grep wlp /tmp/.ifstat.u1000) ]];then
        received=$(grep wlp /tmp/.ifstat.u$UID | awk '{print $7}')
        transmitted=$(grep wlp /tmp/.ifstat.u$UID | awk '{print $9}')
        received=$(( received - $(cat /tmp/wififstatrxzero 2>/dev/null || echo 0) ))
        transmitted=$(( transmitted - $(cat /tmp/wififstattxzero 2>/dev/null || echo 0) ))
        RX="↓$(mean $received)"
        TX="↑$(mean $transmitted)"
    else
        RX=""
        TX=""
    fi
}

mean () {
    units="KMGTP"
    nummean=$(( $(printf $1 | wc -m) / 3 ))
    number=$(echo "$1 / (10 ^ (3 * $nummean) )" | bc -l | cut -c 1-4)
    unit=$(echo $units | cut -c $nummean)
    echo $number$unit
}

case $1 in
    --help)
        echo "Need help? Go fuck yourself!"
        ;;
    --setup-zero-TX)
        grep wlp /tmp/.ifstat.u$UID | awk '{print $9}' > /tmp/wififstattxzero
        ;;
    --setup-zero-RX)
        grep wlp /tmp/.ifstat.u$UID | awk '{print $7}' > /tmp/wififstatrxzero
        ;;
    --toggle-received)
        touch /tmp/wififstattglrx
        ;;
    --toggle-transmitted)
        touch /tmp/wififstattgltx
        ;;
    *)
        if [ "$cable" = "up" ];then
            echo E
        else
            wifi=$(awk 'NR==3 {print $4}' /proc/net/wireless)
            wifi="${wifi%.}"
            wifi="${wifi#-}"
            getifstat
            if [ ! "$wifi" = "" ];then
	        if [ "$wifi" -le 55 ];then
	            echo A "$TX" "$RX"
	        elif [ "$wifi" -le 75 ];then
	            echo B "$TX" "$RX"
	        elif [ "$wifi" -le 85 ];then
	            echo C "$TX" "$RX"
	        else
	            echo D "$TX" "$RX"
	        fi
            else
	        echo
            fi
        fi

esac
