#!/bin/bash

appid=819cc5ba7acaa9c1ad13006d67ca242d
datas=${HOME}/.script/polybar/weatherdir/datas/data
utc=2

icons() {
    case $1 in
        "clear-day") icon="";;
        "clear-night") icon="";;
        "rain") icon="";;
        "snow") icon="";;
        "sleet") icon="";;
        "wind") icon="";;
        "fog") icon="";;
        "cloudy") icon="";;
        "partly-cloudy-day") icon="";;
        "partly-cloudy-night") icon="";;
	"hail") icon= "";;
	"thunderstorm") icon= "";;
	"tornado") icon= "";;
    esac

    echo $icon
}

ceilshit() {
    echo "($1 * $2)" | bc | awk '{print int($1+0.5)}'
}

get_datas(){
    location=$(curl -s ipinfo.io | jq .loc | sed 's/"//g')
    curl -s https://api.darksky.net/forecast/819cc5ba7acaa9c1ad13006d67ca242d/$location?units=ca >$datas
}

current_weather(){
    icon=$(cat $datas | jq .currently.icon | sed 's/"//g')
    humidity=$(cat $datas | jq .currently.humidity) 
    humidity=$(ceilshit $humidity 100)
    temp=$(cat $datas | jq .currently.apparentTemperature) 
    temp=$(ceilshit $temp 1)
    echo "$(icons "$icon")" $humidity% $temp°C
}

forecast_weather(){
    curtimest=$(date +%s)
    i=0
    while [ $i -lt 8 ];do
	timetest=$(cat $datas | jq .daily.data[$i].time)
	isnow=$( echo "( ($curtimest- ($curtimest%86400) ) - $utc * 3600)" | bc )
	(( res= $isnow - $timetest ))
	if [[ $res == 0 ]];then
	    break
	fi
	((i= $i + 1))
    done

    icon=$(cat $datas | jq .daily.data[$i].icon | sed 's/"//g')
    humidity=$(cat $datas | jq .daily.data[$i].humidity) 
    humidity=$(ceilshit $humidity 100)
    tempMin=$(cat $datas | jq .daily.data[$i].apparentTemperatureMin)
    tempMin=$(ceilshit $tempMin 1)
    tempMax=$(cat $datas | jq .daily.data[$i].apparentTemperatureMax) 
    tempMax=$(ceilshit $tempMax 1)

    echo "$(icons "$icon")" $humidity% $tempMin-$tempMax°C    
}

gogogo(){   
if ping -q -c 1 -W 1 1.1.1.1 &>/dev/null; then
    get_datas
    current_weather
else
    forecast_weather
fi
}


while true;do
    gogogo
    
    sleep 600	
done
