--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sam/.config/wpg/wallpapers/XeJvVgc.jpg"

-- Special
background="#2d2d1e"
foreground="#dfe7c3"
cursor="#dfe7c3"

-- Colors
color0="#2d2d1e"
color1="#E1CD7C"
color2="#71BD82"
color3="#73C288"
color4="#90CE9A"
color5="#BBD899"
color6="#89D3A5"
color7="#dfe7c3"
color8="#9ca188"
color9="#E1CD7C"
color10="#71BD82"
color11="#73C288"
color12="#90CE9A"
color13="#BBD899"
color14="#89D3A5"
color15="#dfe7c3"
