# Shell variables
# Generated by 'wal'
wallpaper='/home/sam/.config/wpg/wallpapers/IRHwARX.jpg'

# Special
background='#092A10'
foreground='#f5ccbb'
cursor='#f5ccbb'

# Colors
color0='#092A10'
color1='#A29F58'
color2='#AFA95D'
color3='#FE8D72'
color4='#ECB076'
color5='#F7BF78'
color6='#EB9F8A'
color7='#f5ccbb'
color8='#ab8e82'
color9='#A29F58'
color10='#AFA95D'
color11='#FE8D72'
color12='#ECB076'
color13='#F7BF78'
color14='#EB9F8A'
color15='#f5ccbb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
