# Shell variables
# Generated by 'wal'
wallpaper='/home/sam/.config/wpg/wallpapers/XFItacW.jpg'

# Special
background='#223322'
foreground='#f6edd1'
cursor='#f6edd1'

# Colors
color0='#223322'
color1='#817D9E'
color2='#57A7B8'
color3='#52A8D4'
color4='#63ABD9'
color5='#E5CF99'
color6='#ECD7A0'
color7='#f6edd1'
color8='#aca592'
color9='#817D9E'
color10='#57A7B8'
color11='#52A8D4'
color12='#63ABD9'
color13='#E5CF99'
color14='#ECD7A0'
color15='#f6edd1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
