--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sam/.config/wpg/wallpapers/XFItacW.jpg"

-- Special
background="#223322"
foreground="#f6edd1"
cursor="#f6edd1"

-- Colors
color0="#223322"
color1="#817D9E"
color2="#57A7B8"
color3="#52A8D4"
color4="#63ABD9"
color5="#E5CF99"
color6="#ECD7A0"
color7="#f6edd1"
color8="#aca592"
color9="#817D9E"
color10="#57A7B8"
color11="#52A8D4"
color12="#63ABD9"
color13="#E5CF99"
color14="#ECD7A0"
color15="#f6edd1"
