# Shell variables
# Generated by 'wal'
wallpaper='/home/sam/.config/wpg/wallpapers/lR5i7u6.jpg'

# Special
background='#2c2219'
foreground='#dee9cc'
cursor='#dee9cc'

# Colors
color0='#2c2219'
color1='#929968'
color2='#69B791'
color3='#99A28A'
color4='#B9BB85'
color5='#B6C186'
color6='#C4DFAA'
color7='#dee9cc'
color8='#9ba38e'
color9='#929968'
color10='#69B791'
color11='#99A28A'
color12='#B9BB85'
color13='#B6C186'
color14='#C4DFAA'
color15='#dee9cc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
