--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sam/.config/wpg/wallpapers/HjfJfay.jpg"

-- Special
background="#362121"
foreground="#eadeca"
cursor="#eadeca"

-- Colors
color0="#362121"
color1="#A88879"
color2="#D4955E"
color3="#DAD063"
color4="#E77C9B"
color5="#B49597"
color6="#E4AF99"
color7="#eadeca"
color8="#a39b8d"
color9="#A88879"
color10="#D4955E"
color11="#DAD063"
color12="#E77C9B"
color13="#B49597"
color14="#E4AF99"
color15="#eadeca"
