#!/bin/sh

maildir="${HOME}"/.mail

[ ! -d "$maildir" ] && mkdir "$maildir"

count_mail(){
    num_mail=$(find ~/.mail -regex ".*/[Ii][nN][bB][oO][xX]/new/.*" | wc -l)
    [ ! "$num_mail" = 0 ] && echo "✉ $num_mail"
}

count_mail
