#!/bin/sh

# colors from wpgtk/pywal
. "${HOME}/.cache/wal/colors.sh"
favfile="${HOME}/.script/rome2rio/r2rfav"

touch "$favfile"

dmenucmd="dmenu -nb $color0 -nf $color15 -sb $color0 -sf $color3"
choose="init" # initiate choose to be non zero

until [ -z "$choose" ];do
    choose=$(cat "$favfile" | $dmenucmd -l 10 -i -p "Rome2Rio (S-RET to send): ") || exit
    search="$search"/"$choose"
done

xdg-open "https://www.rome2rio.com/fr/map/$search"
