#!/bin/sh

backup_dir="/home/.backup_zenocloud"

mkdir -p "$backup_dir"

sudo rsync -aAXv --dry-run --delete zenocloud:/ --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} "$backup_dir"
