#!/bin/sh

APPNAME=brightnessbar

type brightnessctl > /dev/null || exit 1

num=$2

[ -z "$num" ] && num=10

case $1 in
    "plus") brightnessctl set $num%+ ;;
    "moins") brightnessctl set $num%- ;;
esac

check=$(cat /tmp/tmpNID)
[ -z "$check" ] && echo 0 > /tmp/tmpNID

LEVEL=$(brightnessctl -m | awk -F "," '{print $4}' )
LEVEL="${LEVEL%%%}"

notify-send "$LEVEL%" -i bright -t 1000 -e -a "$APPNAME" -p -r "$(cat /tmp/tmpNID)" -h int:value:$LEVEL -h boolean:SWAYNC_BYPASS_DND:true > /tmp/tmpNID


brightnessctl -m
