#!/usr/bin/sh

# colors from wpgtk/pywal
. "${HOME}/.cache/wal/colors.sh"
. "${HOME}/.config/zowl.sh"

[ -z $MENU_CMD ] && MENU_CMD="dmenu -nb $color0 -nf $color15 -sb $color3 -sf $color0"

radio=$(cat ${HOME}/.config/music_radios | $MENU_CMD -l 20 -p "Select Radio:")

if [ -n "$radio" ];then
    mpc insert "${radio##* }"
    mpc next || mpc play
fi
