#!/bin/bash

case $1 in
    theme)
        choose=$(wpg --theme | fzf)
        wpg --theme $choose
        ;;
    wall)
        choose=$(wpg -l | fzf)
        wpg -s $choose
        ;;
    *) exit 1
esac

"${HOME}"/.local/bin/wpgscript > /dev/null

exit 0
