#!/bin/sh
time=0.3
length=20

format="%artist% - %title%"
mpc_out=$(mpc --format "$format")

printxfoi(){
    i=0
    while [ $i -lt "$1" ]; do
	printf "$2"
	: $(( i= i + 1 ))
    done
}

if [ $(echo "$mpc_out" | wc -l) -gt 1 ];then

    i=$(date +%s)
    output=$(echo "$mpc_out" | head -n1)

    len=$(printf "$output" | wc -c)
    limit=$(expr "$len" - "$length")

    if [ $limit -gt 0 ]; then

        if [ $(echo "$i % ($limit * 2)" | bc) -ge "$limit" ];then
            shit="-1"
            crap="1"
        else
            shit="1"
            crap="0"
        fi
        norm=$(expr "$i" % "$limit")

        first=$(echo "$shit * $norm + $crap * ($limit - 1) + 1" | bc)
        last=$(expr "$first" + "$length")

        title_artist=$(echo "$output" | cut -c "$first"-"$last")

    else
        foi=$(echo "-1 * $limit + 1" | bc)
        title_artist=$(echo "$output$(printxfoi $foi  )" | sed -s 's/ / /g')
    fi
    playpause=$(echo "$mpc_out" | head -n 2 | tail -n1 | grep -q "^[[]playing[]]" && echo "" || echo "")
    random=$(echo "$mpc_out" | grep -q "random: on" && echo "" || echo " ")
    repeat=$(echo "$mpc_out" | grep -q "repeat: on" && echo "" || echo " ")

    echo " $playpause : $title_artist $random $repeat"
fi
