#!/bin/sh

format="%title% - %artist%"
mpc_out=$(mpc --format "$format")

if [ $(echo "$mpc_out" | wc -l) -gt 1 ];then
    time=0.3
    length=15

    i=$(date +%s)

    output=$(echo "$mpc_out" | head -n1)

    len=$(echo "$output" | wc -c)
    len=$(expr "$len" - 1)
    limit=$(expr "$len" - "$length")

    first=$(expr "$i" % "$limit" + 1)
    last=$(expr "$first" + "$length")


    playpause=$(echo "$mpc_out" | head -n 2 | tail -n1 | grep -q "^[[]playing[]]" && echo "" || echo "")
    random=$(echo "$mpc_out" | grep -q "random: on" && echo "" || echo " ")
    repeat=$(echo "$mpc_out" | grep -q "repeat: on" && echo "" || echo " ")


    title_artist=$(echo "$output" | cut -c "$first"-"$last")

    echo " $playpause : $title_artist $random $repeat"
# else
#     echo ""
fi
