#!/bin/sh

grep -qs "wifi" ~/.config/bar/disabled_module && exit 0 #do nothing if disabled

load_config () {
    if [ -f "${HOME}/.config/wifirc" ];then
        . "${HOME}/.config/wifirc"

        [ -n "$WIFI_TGGL_DEFAULT" ] && touch /tmp/wifi_ifstat_toggle
        [ -n "$WIFI_ZEROS_DEFAULT" ] && format_unit "$WIFI_ZEROS_DEFAULT" > /tmp/wifi_ifstat_rx_zeroplus

        [ -n "$WIFI_ALERT_RX" ] && format_unit "$WIFI_ALERT_RX" > /tmp/wifi_alert_rx
        [ -n "$WIFI_STOP_RX" ] && format_unit "$WIFI_STOP_RX" > /tmp/wifi_stop_rx
    fi
}

mean () {
    units="KMGTP"
    nummean=$(( $(printf $1 | wc -m) / 3 ))
    number=$(echo "$1 / (10 ^ (3 * $nummean) )" | bc -l | cut -c 1-4)
    [ "$nummean" -gt 0 ] && unit=$(echo $units | cut -c "$nummean")
    echo "$number$unit"
}

format_unit () {
    local res=$(echo "$1" | sed 's/K/ * 1000/;s/M/ * 1000000/;s/G/ * 1000000000/;s/T/ * 1000000000000/' | bc)
    echo ${res%%.*}
}

alert_data () {
    received="$1"
    if [ -f /tmp/wifi_stop_rx ]; then
        stop=$(cat /tmp/wifi_stop_rx)
        if [ "$alert" -lt "$received" ];then
            nmcli radio wifi off
            notify-send "ALERT: Data exceeded the max treshold of $(mean $stop), wifi disabled"
        fi
    fi

    if [ -f /tmp/wifi_alert_rx ]; then
        alert=$(cat /tmp/wifi_alert_rx)
        if [ "$alert" -lt "$received" ];then
            notify-send "ALERT Current data $(mean $received) greater than $(mean $alert)"
        fi
    fi
}

setup_zero () {
    get_bigdev
    read rxzero txzero <<EOF
$(grep "$bigdev" /tmp/.ifstat.u$UID | awk '{print $7 " " $9}')
EOF
    echo $txzero > /tmp/wifi_ifstat_tx_zero
    [ -n "$1" ] && echo $(format_unit "$1") > /tmp/wifi_ifstat_rx_zeroplus || rm -f /tmp/wifi_ifstat_rx_zeroplus
    echo $rxzero > /tmp/wifi_ifstat_rx_zero
}

getifstat () {
    ifstat -n
    if [ -n "$(grep "$bigdev" /tmp/.ifstat.u"$UID")" ];then
        read received transmitted <<EOF
$(grep "$bigdev" /tmp/.ifstat.u"$UID" | awk '{print $7 " " $9}')
EOF
        recminus=$(cat /tmp/wifi_ifstat_rx_zero 2>/dev/null)
        transminus=$(cat /tmp/wifi_ifstat_tx_zero 2>/dev/null)
        [ -z "$recminus" ] && recminus=0
        [ -z "$transminus" ] && transminus=0

        recplus=$(cat /tmp/wifi_ifstat_rx_zeroplus 2>/dev/null)
        [ -z "$recplus" ] && recplus=0

        received=$(( received - recminus + recplus))
        transmitted=$(( transmitted - transminus ))
        alert_data "$received"

        RX="↓$(mean $received)"
        TX="↑$(mean $transmitted)"
    fi
}

get_bigdev () {

    ethdev=$(ip link | grep -E "[0-9]: e.*: " | grep UP | sed 's/[0-9]: \(e.*\): .*/\1/')
    wifidev=$(ip link | grep -E "[0-9]: w.*: " | grep UP | sed 's/[0-9]: \(w.*\): .*/\1/')

    [ -n "$ethdev" ] && bigdev="$ethdev"
    [ -n "$wifidev" ] && bigdev="$wifidev"

}


print_wifi () {

    ethdev=$(ip link | grep -E "[0-9]: e.*: " | grep UP | sed 's/[0-9]: \(e.*\): .*/\1/')
    wifidev=$(ip link | grep -E "[0-9]: w.*: " | grep UP | sed 's/[0-9]: \(w.*\): .*/\1/')

    if [ -n "$ethdev" ];then
        [ "$(cat /sys/class/net/$ethdev/operstate)" = "up" ] && output="" && bigdev="$ethdev"
    fi

    if [ -n "$wifidev" ];then
        wifi=$(awk 'NR==3 {print substr($4,2,2)}' /proc/net/wireless)
        bigdev="$wifidev"
        if [ -n "$wifi" ];then
            if [ "$wifi" -le 55 ];then
                output=""
            elif [ "$wifi" -le 75 ];then
                output=""
            elif [ "$wifi" -le 85 ];then
                output=""
            else
                output=""
            fi
        fi
    fi
    [ -f /tmp/wifi_ifstat_toggle ] && getifstat && output="$output $RX $TX"
    echo "$output"
}

case $1 in
    --help) echo "TODO" ;;
    --prompt-zeros)

        . "${HOME}/.cache/wal/colors.sh"
        DMENU_CMD="dmenu -nb $color0 -nf $color15 -sb $color0 -sf $color3"

        zero=$(echo | $DMENU_CMD -p "Zero to set:")
        setup_zero "$zero"
        ;;
    --setup-zeros)
        setup_zero "$2"
        ;;
    --toggle-ifstat)
        if [ -f /tmp/wifi_ifstat_toggle ];then
            rm /tmp/wifi_ifstat_toggle && echo wifi ifstat disabled
        else
            touch /tmp/wifi_ifstat_toggle && echo wifi ifstat enabled
        fi
        ;;
    --load-config)
        load_config ;;
    *)
        print_wifi
esac
