[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 2, y = 2 }
opacity = 0.6
dynamic_padding = false
decorations = "full"
startup_mode = "Windowed"
title = "term"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }
size = 11.0

[colors]
[colors.primary]
background = "0x1d2021"
foreground = "0xebdbb2"

[colors.normal]
black = "0x282828"
red = "0xcc241d"
green = "0x98971a"
yellow = "0xd79921"
blue = "0x458588"
magenta = "0xb16286"
cyan = "0x689d6a"
white = "0xa89984"

[colors.bright]
black = "0x928374"
red = "0xfb4934"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xebdbb2"

[cursor]
style = "Block"
unfocused_hollow = true

