[general]
import = [
    "~/.config/alacritty/gruvbox_colors.toml",
    "~/.config/alacritty/colors.toml",
]

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 2, y = 2 }
opacity = 0.6
dynamic_padding = false
decorations = "full"
startup_mode = "Windowed"
title = "term"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }
size = 11.0

[cursor]
style = "Block"
unfocused_hollow = true
