;;;;;;;;;;;;;;;;;
;; ACTION CODE ;;
;;;;;;;;;;;;;;;;;

(defvar hpns-alists-list
  '("Action" "Function" "Abbrev" "Currency" "Incident")
  "List of Alist")

(defvar hpns-alists-action-code
  '((0 . "Approved")
    (100 . "Do not honour")
    (101 . "Expired card")
    (104 . "Restricted card")
    (106 . "Allowable number of PIN tries exceeded")
    (110 . "Invalid amount")
    (111 . "Invalid card number (no such number")
    (112 . "Pin Data Required")
    (115 . "Requested Function not supported")
    (116 . "Not sufficient funds")
    (117 . "Incorrect PIN")
    (118 . "No card record")
    (119 . "Transaction not permitted to cardholder")
    (120 . "Transaction not permitted to terminal")
    (121 . "Exceeds withdrawal amount limit")
    (122 . "Security Violation")
    (123 . "Exceeds withdrawal frequency limit")
    (125 . "Card not effective / not activated")
    (126 . "Invalid PIN Block")
    (128 . "PIN Key Sync Error (can be used when key unwrap fails in situations where the PIN Session Key is transported using AES Key Wrapping")
    (129 . "Suspected counterfeit card")
    (181 . "Invalid BEPAF")
    (182 . "No PIN transaction velocity limit exceeded")
    (183 . "EMV data Incorrect")
    (184 . "EMV data inconsistent. Can be used to indicate a failure during ATC check by the issuer")
    (185 . "Fallback transactions not permitted for this service by issuer (not used as Fallback indicator is not defined in P22")
    (186 . "Incorrect EMV cryptogram (ARQC")
    (187 . "Card Periodic limit exceeded")
    (188 . "Card Daily limit exceeded")
    (189 . "Account Periodic limit exceeded")
    (190 . "Account Daily limit exceeded")
    (191 . "Incompatibility between card & Account")
    (192 . "Card Not affected (card not yet linked to an account")
    (193 . "Card Disaffected (or deactivated")
    (194 . "Another transaction is busy for this card")
    (195 . "Another transaction is busy for this account")
    (196 . "Another PIN Change is busy")
    (197 . "Issuer in Opposition")
    (198 . "Wallet initiated payment refused / 3Dsecure required")
    (200 . "Pick up – Card swallowed by the ATM")
    (202 . "Suspected Fraud, Pick up (ATM only)")
    (208 . "Lost card, Pick-up (ATM only)")
    (209 . "Stolen card, Pick-up (ATM only)")
    (210 . "Suspected counterfeit card, Pickup (ATM only)")
    (211 . "Card in Opposition, Pickup (ATM only")
    (212 . "Account in Opposition, Pickup (ATM only")
    (500 . "Reconciliation successfully processed")
    (800 . "Accepted (Network messages")
    (902 . "Invalid transaction")
    (905 . "Acquirer not supported by switch")
    (908 . "Transaction destination cannot be found for routing")
    (909 . "System malfunction")
    (911 . "Time out of issuer response")
    (912 . "Card issuer unavailable")
    (940 . "Problem or time out at card restitution")
    (941 . "The cardholder forgot his card")
    (942 . "Time-out on the response to the authorization request message")
    (943 . "STOP due to the client / transaction interrupted by the client / transaction cancelled (also time out on input")
    (944 . "Technical problem during notes distribution. Transaction cancelled")
    (945 . "Problem during parameters update in the card (Pin Change")
    (946 . "Transaction aborted by the acquirer for its own reason")
    (948 . "Transaction denied by EMV card (AAC generated or ARPC rejected")
    (950 . "The card holder forgot his notes")
    (951 . "Local incident during partial approval on POS: cardholder has not confirmed the partial approval of the transaction")))

;;;;;;;;;;;;;;;;;;;
;; FUNCTION CODE ;;
;;;;;;;;;;;;;;;;;;;

(defvar hpns-alists-function-code
  '((122 . "Cash withdrawal")
    (222 . "Cash withdrawal")
    (102 . "Cash withdrawal")
    (124 . "PIN change")
    (224 . "PIN change")
    (104 . "PIN change")
    (126 . "Balance Consultation")
    (106 . "Balance Consultation")
    (127 . "PIN Setting")
    (227 . "PIN Setting")
    (107 . "PIN Setting")
    (128 . "PIN Regularization")
    (228 . "PIN Regularization")
    (108 . "PIN Regularization")
    (129 . "Card Update")
    (229 . "Card Update")
    (109 . "Card Update")
    (900 . "Stand-alone incident")
    (134 . "EMV Card Validity Check")
    (114 . "EMV Card Validity Check")
    (135 . "EMV Cash Deposit Private (RFU)")
    (235 . "EMV Cash Deposit Private (RFU)")
    (115 . "EMV Cash Deposit Private (RFU)")
    (500 . "Reconciliation balance (period closing)"))
  "Alist for function code")

;;;;;;;;;;;;;;;;;;;;
;; CURRENCY CODES ;;
;;;;;;;;;;;;;;;;;;;;

(defvar hpns-alists-currency-code
  '(("784" . "AED") ("971" . "AFN") ("008" . "ALL")
    ("051" . "AMD") ("532" . "ANG") ("973" . "AOA")
    ("032" . "ARS") ("036" . "AUD") ("533" . "AWG")
    ("944" . "AZN") ("977" . "BAM") ("052" . "BBD")
    ("050" . "BDT") ("975" . "BGN") ("048" . "BHD")
    ("108" . "BIF") ("060" . "BMD") ("096" . "BND")
    ("068" . "BOB") ("984" . "BOV") ("986" . "BRL")
    ("044" . "BSD") ("064" . "BTN") ("072" . "BWP")
    ("933" . "BYN") ("084" . "BZD") ("124" . "CAD")
    ("976" . "CDF") ("947" . "CHE") ("756" . "CHF")
    ("948" . "CHW") ("990" . "CLF") ("152" . "CLP")
    ("156" . "CNY") ("170" . "COP") ("970" . "COU")
    ("188" . "CRC") ("931" . "CUC") ("192" . "CUP")
    ("132" . "CVE") ("203" . "CZK") ("262" . "DJF")
    ("208" . "DKK") ("214" . "DOP") ("012" . "DZD")
    ("818" . "EGP") ("232" . "ERN") ("230" . "ETB")
    ("978" . "EUR") ("242" . "FJD") ("238" . "FKP")
    ("826" . "GBP") ("981" . "GEL") ("936" . "GHS")
    ("292" . "GIP") ("270" . "GMD") ("324" . "GNF")
    ("320" . "GTQ") ("328" . "GYD") ("344" . "HKD")
    ("340" . "HNL") ("191" . "HRK") ("332" . "HTG")
    ("348" . "HUF") ("360" . "IDR") ("376" . "ILS")
    ("356" . "INR") ("368" . "IQD") ("364" . "IRR")
    ("352" . "ISK") ("388" . "JMD") ("400" . "JOD")
    ("392" . "JPY") ("404" . "KES") ("417" . "KGS")
    ("116" . "KHR") ("174" . "KMF") ("408" . "KPW")
    ("410" . "KRW") ("414" . "KWD") ("136" . "KYD")
    ("398" . "KZT") ("418" . "LAK") ("422" . "LBP")
    ("144" . "LKR") ("430" . "LRD") ("426" . "LSL")
    ("434" . "LYD") ("504" . "MAD") ("498" . "MDL")
    ("969" . "MGA") ("807" . "MKD") ("104" . "MMK")
    ("496" . "MNT") ("446" . "MOP") ("929" . "MRU")
    ("480" . "MUR") ("462" . "MVR") ("454" . "MWK")
    ("484" . "MXN") ("979" . "MXV") ("458" . "MYR")
    ("943" . "MZN") ("516" . "NAD") ("566" . "NGN")
    ("558" . "NIO") ("578" . "NOK") ("524" . "NPR")
    ("554" . "NZD") ("512" . "OMR") ("590" . "PAB")
    ("604" . "PEN") ("598" . "PGK") ("608" . "PHP")
    ("586" . "PKR") ("985" . "PLN") ("600" . "PYG")
    ("634" . "QAR") ("946" . "RON") ("941" . "RSD")
    ("643" . "RUB") ("646" . "RWF") ("682" . "SAR")
    ("090" . "SBD") ("690" . "SCR") ("938" . "SDG")
    ("752" . "SEK") ("702" . "SGD") ("654" . "SHP")
    ("694" . "SLL") ("706" . "SOS") ("968" . "SRD")
    ("728" . "SSP") ("930" . "STN") ("222" . "SVC")
    ("760" . "SYP") ("748" . "SZL") ("764" . "THB")
    ("972" . "TJS") ("934" . "TMT") ("788" . "TND")
    ("776" . "TOP") ("949" . "TRY") ("780" . "TTD")
    ("901" . "TWD") ("834" . "TZS") ("980" . "UAH")
    ("800" . "UGX") ("840" . "USD") ("997" . "USN")
    ("940" . "UYI") ("858" . "UYU") ("860" . "UZS")
    ("937" . "VEF") ("704" . "VND") ("548" . "VUV")
    ("882" . "WST") ("950" . "XAF") ("951" . "XCD")
    ("960" . "XDR") ("952" . "XOF") ("953" . "XPF")
    ("994" . "XSU") ("965" . "XUA") ("886" . "YER")
    ("710" . "ZAR") ("967" . "ZMW") ("932" . "ZWL"))
  "Alist for currency code")

;;;;;;;;;;;;;;;;;;;;
;; INCIDENT CODES ;;
;;;;;;;;;;;;;;;;;;;;

(defvar hpns-alists-incident-code
  '((0 .  "Operation authorized without restriction by the eW host or operation succeeded on the ATM")
    (5 . "The OLTB issuer rejects the transaction for its own reason")
    (6 . "The issuer rejects the transaction (other brands than Bancontact)")
    (7 . "Obsolete")
    (11 . "Zero amount transaction")
    (12 . "Not allowed operation")
    (13 . "Obsolete")
    (14 . "ISO-2 track or PAN incorrect")
    (15 . "The card does not exist in the eW database")
    (17 . "Unknown card (other brands than Bancontact)")
    (18 . "Obsolete")
    (20 . "Obsolete")
    (21 . "Obsolete")
    (22 . "Account periodic limit exceeded")
    (23 . "Card periodic limit exceeded")
    (24 . "Card daily limit exceeded")
    (25 . "Account daily limit exceeded")
    (26 . "Obsolete")
    (40 . "Card in group opposition: swallow card")
    (41 . "Card in opposition: swallow card")
    (42 . "Card should have been swallowed during preceding transaction")
    (43 . "Card in account opposition: swallow card")
    (44 . "EMV blocked card")
    (45 . "Card in group opposition: restitute card")
    (46 . "Card in opposition: restitute card")
    (47 . "Card in account opposition: restitute card")
    (50 . "Incompatibility between card and account")
    (51 . "Available not sufficient")
    (52 . "Obsolete")
    (53 . "Card expired (less than 6 months if R3bc card)")
    (54 . "Card expired (more than 6 months if R3bc card) (Y)12")
    (12 . "The 6 month delay is only for Bancontact non-EMV cards. For other cards only Incident Code")
    (54 . "is used. Swallowing depends on the issuer's decision.")
    (55 . "Card not affected")
    (56 . "Card disaffected")
    (57 . "The transaction type does not match with the card profile; the card has no access.")
    (58 . "Another PIN change is busy (on another terminal)")
    (59 . "PIN change refused by issuer network")
    (60 . "Test card or terminal")
    (61 . "Card has expired since a maximum of 6 months")
    (63 . "Bad authentication certificate (IEP-TX-CRE-PUR-AC)")
    (64 . "Another transaction is busy for this card")
    (65 . "Another transaction is busy on the same account")
    (75 . "Number of PIN trials exceeded. (on the eW host)")
    (76 . "PIN incorrect – no PIN trial any more (in the card – PIN off-line)")
    (94 . "Communication problem with the issuer (not OLTB connection)")
    (95 . "Communication problem with the issuer (OLTB connection)")
    (96 . "DEP problem at eW")
    (97 . "Central system problem at eW")
    (109 . "The requested amount is lower than the minimum authorized amount")
    (110 . "The requested amount is higher than the maximum authorized amount")
    (113 . "Invalid currency")
    (130 .  "Wrong PIN, still 1 PIN trial (on the eW host).")
    (131 .  "Wrong PIN, still 2 PIN trial (on the eW host)")
    (132 .  "Wrong PIN (other brands than Bancontact non-EMV)")
    (140 .  "The cardholder forgot the notes.")
    (141 .  "Obsolete.")
    (143 .  "Incoherence ISO-2 track and the data of the ISO-2 track copy in the chip.")
    (144 .  "Problem or time out at card restitution.")
    (145 .  "The cardholder forgot his card.")
    (146 .  "Time-out on the response to the authorization request message.")
    (147 .  "Fraud card presented.")
    (148 .  "There is no PIN trial left in the card. (off-line PIN)")
    (149 .  "Incident during the update of the number of PIN trials in the chip.")
    (150 .  "Obsolete.")
    (151 .  "Obsolete.")
    (152 .  "STOP due to the client/transaction interrupted by the client/transaction cancelled (also time out on input).")
    (156 . "Both new PIN and control PIN are not identical (PIN change)")
    (157 . "Technical problem during notes distribution. Transaction cancelled.")
    (158 . "Problem during PIN rewriting in the card")
    (159 . "Problem during parameters update in the card")
    (160 . "ISO-2 track unreadable")
    (161 . "Transaction aborted by the acquirer for its own reason")
    (162 . "Incorrect certificate (R4 MAC or ARQC)")
    (163 . "Transaction denied by EMV card (AAC generated or ARPC rejected)")
    (164 . "PIN setting allowed time elapsed")
    (165 . "NO PIN setting window open")
    (166 . "Invalid authorization code"))
  "Incident code alist")

;;;;;;;;;;;;
;; ABRREV ;;
;;;;;;;;;;;;

(defvar hpns-alists-abbrev
  '(("HPNS" .  "H(ewlett)P(ackard) Non Stop")
    ("TA" .  "Technical Authentification")
    ("PTI" .  "Petrol")
    ("PTO" .  "Petrol")
    ("POS" .  "Point on sale (au magasin)")
    ("ATM" .  "Automated Teller Machine")
    ("NR" .  "Non regression")
    ("eW" .  "equensWorldline")
    ("BTM" .  "Business Team Manager (Thierry Louis)")
    ("UAT" .  "SPROG3")
    ("INF" .  "SPROG5")
    ("FCT" .  "SPROG4")
    ("MTI" .  "Message Type Identifier")
    ("IBAN" .  "International Bank Account Number")
    ("EMV" .  "Europay, MasterCard, Visa (international standard for chip transactions)")
    ("BIN" .  "Les 6 premiers chiffres du PAN")
    ("BCMC" .  "Bancontact")
    ("MAS" .  "mastercard")
    ("VTS" .  "visa")
    ("NO-CVM" .  "No pin")
    ("CLS" .  "Contact less (TODO  A VERIFIER)")
    ("TPPN" .  "Transaction Protocol for Private Networks")
    ("OLTB" .  "Online To Bank")
    ("OLTI" .  "Online To Issuer")
    ("AAC" .  "Application Authentication Cryptogram")
    ("AID" .  "Acquiring Institution iDentification code")
    ("AID" .  "Application IDentifier (EMV)")
    ("ARPC" .  "Authorization Response Cryptogram")
    ("ARQC" .  "Authorization Request Cryptogram")
    ("ATC" .  "Application Transaction Counter")
    ("BAPOF" .  "Base PIN Offset")
    ("BBAN" .  "Basic Bank Account Number")
    ("BCD" .  "Binary Coded Decimal")
    ("CEC" .  "Centre for Exchange and Clearing")
    ("CPP" .  "Common Purchase Point")
    ("CVC" .  "Card Validity Check")
    ("CVM" .  "Card Verification Method")
    ("DEP" .  "Data Encryption Peripheral")
    ("HSM" .  "Hardware Security Module")
    ("ICC" .  "Integrated Circuit Card")
    ("IFD" .  "Interface Device (Serial Number)")
    ("IPS" .  "Intraprocessor Switch")
    ("LAC" .  "Logical Application Channel")
    ("MAC" .  "Message Authentication Code")
    ("MC" .  "MasterCard")
    ("OLTP" .  "Online To Third Party")
    ("PDS" .  "Private Data Subelement")
    ("PIX" .  "Proprietary Application Identification Extension")
    ("PNAD" .  "Private Network Operation Advices")
    ("PNAU" .  "Private Network on-line Authorization")
    ("POS" .  "Point Of Sales")
    ("RID" .  "Registered Application Provider Identification")
    ("SDD" .  "Structured Discretionary Data")
    ("STAN" .  "System Trace Audit Number")
    ("TC" .  "Transaction Certificate")
    ("TLV" .  "Tag, Length, Value")
    ("TR" .  "Transaction Response")
    ("a" .  "Pathmon SPROG4")
    ("n" .  "Pathmon SPROG4")
    ("b" .  "Pathmon SPROG3")
    ("g" .  "Pathmon SPROG3")
    ("k" .  "Pathmon SPROG5")
    ("o" .  "Pathmon SPROG5")
    ))

;;;;;;;;;;;;;;;;;;;
;; TRACES FIELDS ;;
;;;;;;;;;;;;;;;;;;;

(defvar hpns-alists-olti-field
  '((1  "Bitmap :" "8")
    (2  "PAN : "  "19.")
    (3  "Process Code : "  "6")
    (4  "Amount : "  "12")
    (6  "Amount (cardholder billing) : "  "12")
    (7  "Datetime : "  "10")
    (10 "Conversion rate, cardholder, billing : "  "8")
    (11  "STAN : "  "6")
    (12  "Datetime local : "  "12")
    (14 "Date, expiration : "  "4")
    (22  "Point of Service data code : "  "12")
    (23  "Card Sequence Number : "  "3")
    (24  "Function code : "  "3")
    (25 "Message reason code : "  "4")
    (26 "Card acceptor business code : "  "4")
    (28 "Date, reconciliation : "  "6")
    (30 "Amounts, original : "  "24")
    (32  "Acquirer institution identification code : "  "11.")
    (33 "Forwarding institution identification code : "  "11.")
    (35  "ISO track 2 data : "  "37.")
    (37  "Retrieval reference number : "  "12")
    (38  "Approval code : "  "6")
    (39  "Auth resp code/Action Code : "  "3")
    (41  "Card acceptor terminal identification Code : "  "8")
    (42  "Card acceptor identification Code : "  "15")
    (43  "Card acceptor name/location : "  "99.")
    (44 "Additional response data : "  "99.")
    (48  "Additional data, private : "  "999.")
    (49  "Currency code, transaction : "  "3")
    (50  "Currency code : "  "3")
    (51 "Currency code, cardholder, billing :" "3")
    (52  "Pin data : "  "8")
    (53  "Security related control information : ")
    (54 "Amounts, additional : "  "120.")
    (55  "ICC system related data : "  "255.")
    (56 "Original data elements : "  "35.")
    (64  "Message authentication code (MAC) : ")
    (75 "Credit, reversal number : "  "10")
    (76 "Debits, number : "  "10")
    (87 "Credit, reversal amount : "  "16")
    (88 "Debits, amount : "  "16")
    (93 "Transaction destination institution ID code : "  "11.")
    (94 "Transaction originator institution ID code : "  "11.")
    (97 "Amount, net reconciliation : "  "16")
    (100 "Receiving institution ID code : "  "11.")
    (121 "Additional data – private : "  "999.")
    (124 "De124 – Information text : "  "255.")
    (128 "Mac : "  "8")))

;;;;;;;;;;
;; TPPN ;;
;;;;;;;;;;


(defvar hpns-alist-tppn-incident-code
  '((0 .  "Operation authorized without restriction by the eW host or operation succeeded on the ATM")
    (5 . "The OLTB issuer rejects the transaction for its own reason")
    (6 . "The issuer rejects the transaction (other brands than Bancontact)")
    (7 . "Obsolete")
    (11 . "Zero amount transaction")
    (12 . "Not allowed operation")
    (13 . "Obsolete")
    (14 . "ISO-2 track or PAN incorrect")
    (15 . "The card does not exist in the eW database")
    (17 . "Unknown card (other brands than Bancontact)")
    (18 . "Obsolete")
    (20 . "Obsolete")
    (21 . "Obsolete")
    (22 . "Account periodic limit exceeded")
    (23 . "Card periodic limit exceeded")
    (24 . "Card daily limit exceeded")
    (25 . "Account daily limit exceeded")
    (26 . "Obsolete")
    (40 . "Card in group opposition: swallow card")
    (41 . "Card in opposition: swallow card")
    (42 . "Card should have been swallowed during preceding transaction")
    (43 . "Card in account opposition: swallow card")
    (44 . "EMV blocked card")
    (45 . "Card in group opposition: restitute card")
    (46 . "Card in opposition: restitute card")
    (47 . "Card in account opposition: restitute card")
    (50 . "Incompatibility between card and account")
    (51 . "Available not sufficient")
    (52 . "Obsolete")
    (53 . "Card expired (less than 6 months if R3bc card)")
    (54 . "Card expired (more than 6 months if R3bc card) (Y)12")
    (12 . "The 6 month delay is only for Bancontact non-EMV cards. For other cards only Incident Code")
    (54 . "is used. Swallowing depends on the issuer's decision.")
    (55 . "Card not affected")
    (56 . "Card disaffected")
    (57 . "The transaction type does not match with the card profile; the card has no access.")
    (58 . "Another PIN change is busy (on another terminal)")
    (59 . "PIN change refused by issuer network")
    (60 . "Test card or terminal")
    (61 . "Card has expired since a maximum of 6 months")
    (63 . "Bad authentication certificate (IEP-TX-CRE-PUR-AC)")
    (64 . "Another transaction is busy for this card")
    (65 . "Another transaction is busy on the same account")
    (75 . "Number of PIN trials exceeded. (on the eW host)")
    (76 . "PIN incorrect – no PIN trial any more (in the card – PIN off-line)")
    (94 . "Communication problem with the issuer (not OLTB connection)")
    (95 . "Communication problem with the issuer (OLTB connection)")
    (96 . "DEP problem at eW")
    (97 . "Central system problem at eW")
    (109 . "The requested amount is lower than the minimum authorized amount")
    (110 . "The requested amount is higher than the maximum authorized amount")
    (113 . "Invalid currency")
    (130 .  "Wrong PIN, still 1 PIN trial (on the eW host).")
    (131 .  "Wrong PIN, still 2 PIN trial (on the eW host)")
    (132 .  "Wrong PIN (other brands than Bancontact non-EMV)")
    (140 .  "The cardholder forgot the notes.")
    (141 .  "Obsolete.")
    (143 .  "Incoherence ISO-2 track and the data of the ISO-2 track copy in the chip.")
    (144 .  "Problem or time out at card restitution.")
    (145 .  "The cardholder forgot his card.")
    (146 .  "Time-out on the response to the authorization request message.")
    (147 .  "Fraud card presented.")
    (148 .  "There is no PIN trial left in the card. (off-line PIN)")
    (149 .  "Incident during the update of the number of PIN trials in the chip.")
    (150 .  "Obsolete.")
    (151 .  "Obsolete.")
    (152 .  "STOP due to the client/transaction interrupted by the client/transaction cancelled (also time out on input).")
    (156 . "Both new PIN and control PIN are not identical (PIN change)")
    (157 . "Technical problem during notes distribution. Transaction cancelled.")
    (158 . "Problem during PIN rewriting in the card")
    (159 . "Problem during parameters update in the card")
    (160 . "ISO-2 track unreadable")
    (161 . "Transaction aborted by the acquirer for its own reason")
    (162 . "Incorrect certificate (R4 MAC or ARQC)")
    (163 . "Transaction denied by EMV card (AAC generated or ARPC rejected)")
    (164 . "PIN setting allowed time elapsed")
    (165 . "NO PIN setting window open")
    (166 . "Invalid authorization code"))
  "Incident code alist")

(defvar hpns-alists-tppn-fields
  '((1  "Bitmap :" "8")
    (2  "PAN : "  "19.")
    (3  "Process Code : "  "6")
    (4  "Amount : "  "12")
    (6  "Amount (cardholder billing) : "  "12")
    (7  "Datetime : "  "10")
    (10 "Conversion rate, cardholder, billing : "  "8")
    (11  "STAN : "  "6")
    (12  "Datetime local : "  "12")
    (14 "Date, expiration : "  "4")
    (22  "Point of Service data code : "  "12")
    (23  "Card Sequence Number : "  "3")
    (24  "Function code : "  "3")
    (25 "Message reason code : "  "4")
    (26 "Card acceptor business code : "  "4")
    (28 "Date, reconciliation : "  "6")
    (30 "Amounts, original : "  "24")
    (32  "Acquirer institution identification code : "  "11.")
    (33 "Forwarding institution identification code : "  "11.")
    (35  "ISO track 2 data : "  "37.")
    (37  "Retrieval reference number : "  "12")
    (38  "Approval code : "  "6")
    (39  "Auth resp code/Action Code : "  "3")
    (41  "Card acceptor terminal identification Code : "  "8")
    (42  "Card acceptor identification Code : "  "15")
    (43  "Card acceptor name/location : "  "99.")
    (44 "Additional response data : "  "99.")
    (48  "Additional data, private : "  "999.")
    (49  "Currency code, transaction : "  "3")
    (50  "Currency code : "  "3")
    (51 "Currency code, cardholder, billing :" "3")
    (52  "Pin data : "  "8")
    (53  "Security related control information : ")
    (54 "Amounts, additional : "  "120.")
    (55  "ICC system related data : "  "255.")
    (56 "Original data elements : "  "35.")
    (64  "Message authentication code (MAC) : ")
    (75 "Credit, reversal number : "  "10")
    (76 "Debits, number : "  "10")
    (87 "Credit, reversal amount : "  "16")
    (88 "Debits, amount : "  "16")
    (93 "Transaction destination institution ID code : "  "11.")
    (94 "Transaction originator institution ID code : "  "11.")
    (97 "Amount, net reconciliation : "  "16")
    (100 "Receiving institution ID code : "  "11.")
    (121 "Additional data – private : "  "999.")
    (124 "De124 – Information text : "  "255.")
    (128 "Mac : "  "8")))

;;;;;;;;;;
;; VISA ;;
;;;;;;;;;;

(defvar hpns-alists-visa-fields
  '((2 "Primary Account Number (PAN)" "11.")
    (3 "Processing Code" "3")
    (4 "Amount; Transaction" "6")
    (6 "Amount; Cardholder Billing" "6")
    (7 "Transmission Date and Time" "5")
    (8 "Amount; Cardholder Billing Fee (not used)" "4")
    (10 "Conversion Rate; Cardholder Billing" "4")
    (11 "System Trace Audit Number" "3")
    (12 "Time; Local Transaction" "3")
    (13 "Date; Local Transaction" "2")
    (14 "Date; Expiration" "2")
    (17 "Date; Capture" "2")
    (18 "Merchant Type" "2")
    (19 "Acquiring Institution Country Code" "2")
    (20 "PAN Extended; Country Code" "2")
    (22 "POS Entry Mode Code" "2")
    (23 "Card Sequence Number" "2")
    (24 "Network International Identifier (not used)" "2")
    (25 "POS Condition Code" "1")
    (26 "POS PIN Capture Code" "1")
    (27 "Authorization Identification Response Length (not used)" "1")
    (28 "Amount; Transaction Fee" "9")
    (29 "Amount; Settlement Fee (not used)" "9")
    (30 "Amount; Transaction Processing Fee (not used)" "9")
    (31 "Amount; Settlement Processing Fee (not used)" "9")
    (32 "Acquiring Institution Identification Code" "7.")
    (33 "Forwarding Institution Identification Code" "7.")
    (35 "Track 2 Data" "20.")
    (36 "Track 3 Data (not used)" "53.")
    (37 "Retrieval Reference Number (RRN)" "12")
    (38 "Authorization Identification Response" "6")
    (39 "Response Code" "2")
    (41 "Card Acceptor Terminal Identification" "8")
    (42 "Card Acceptor Identification Code" "15")
    (43 "Card Acceptor Name/Location" "40")
    (44 "Additional Response Data" "26.")
    (45 "Track 1 Data" "77.")
    (46 "Additional Data—ISO (not used)" "256.")
    (47 "Additional Data—National (not used)" "256.")
    (48 "Additional Data—Private" "256.")
    (49 "Currency Code; Transaction" "2")
    (51 "Currency Code; Cardholder Billing" "2")
    (52 "PIN Data" "8")
    (53 "Security-Related Control Information" "8")
    (54 "Additional Amounts" "121.")
    (55 "ICC Related Data" "256.")
    (56 "Payment Account Reference Data" "256.")
    (57 "Reserved—National (not used)" "256.")
    (58 "Reserved—National (not used)" "256.")
    (59 "National POS Geographic Data" "15.")
    (60 "Additional POS Information" "7.")
    (61 "Other Amounts" "19.")
    (62 "Custom Payment Service Fields" "256.")
    (63 "VIP Private" "256.")
    (67 "Extended Payment Code (not used)" "1")
    (68 "Receiving Institution Country Code" "2")
    (70 "Network Management Information Code" "2")
    (71 "Message Number (not used)" "2")
    (72 "Message Number Last (not used)" "2")
    (73 "Date; Action" "3")
    (78 "Transfer; Number (not used)" "5")
    (79 "Transfer; Reversal Number (not used)" "5")
    (80 "Inquiries; Number (not used)" "5")
    (81 "Authorizations; Number (not used)" "5")
    (82 "Credits; Processing Fee Amount (not used)" "6")
    (83 "Credits; Transaction Fee Amount (not used)" "6")
    (84 "Debits; Processing Fee Amount (not used)" "6")
    (85 "Debits; Transaction Fee Amount (not used)" "6")
    (90 "Original Data Elements" "21")
    (91 "File Update Code" "1")
    (92 "File Security Code" "2")
    (94 "Service Indicator (not used)" "7")
    (95 "Replacement Amounts" "42")
    (98 "Payee (not used)" "25")
    (100 "Receiving Institution Identification Code" "7.")
    (101 "File Name" "18.")
    (102 "Account Identification 1" "29.")
    (103 "Account Identification 2" "29.")
    (104 "Transaction Description" "256.")
    (105 "Reserved ISO (not used)" "256.")
    (106 "Reserved ISO (not used)" "256.")
    (107 "Reserved ISO (not used)" "256.")
    (108 "Reserved ISO (not used)" "256.")
    (109 "Reserved ISO (not used)" "256.")
    (110 "Reserved ISO (not used)" "256.")
    (111 "Reserved ISO (not used)" "256.")
    (112 "Reserved National (not used)" "256.")
    (113 "Reserved National (not used)" "256.")
    (114 "Reserved National (not used)" "256.")
    (115 "Additional Trace Data" "25.")
    (116 "Card Issuer Reference Data" "256.")
    (117 "National Use" "256.")
    (118 "Intra-Country Data" "256.")
    (120 "Auxiliary Transaction Data (TLV Format)" "256.")
    (121 "Issuing Institution Identification Code" "12.")
    (123 "Verification Data" "30.")
    (125 "Supporting Information" "256.")
    (126 "Visa Private-Use Fields" "256.")
    (127 "File Maintenance" "256.")
    (130 "Terminal Capability Profile" "3")
    (131 "Terminal Verification Results (TVR)" "5")
    (132 "Unpredictable Number" "4")
    (133 "Terminal Serial Number" "8")
    (134 "Visa Discretionary Data" "256.")
    (134 "Visa Discretionary Data; Format 1" "16.")
    (134 "Visa Discretionary Data; Format 2" "33.")
    (135 "Issuer Discretionary Data" "16.")
    (136 "Cryptogram" "8")
    (137 "Application Transaction Counter" "2")
    (138 "Application Interchange Profile" "2")
    (139 "ARPC Response Cryptogram & Code" "10")
    (139 "Format 1—VIS Usage; ARPC Response Cryptogram & Code" "10")
    (139 "Format 2—CCD Usage; Issuer Authentication Data" "10")
    (140 "Issuer Authentication Data" "256.")
    (140 "Format 1; VIS Usage: Issuer Authentication Data" "11.")
    (140 "Format 2; CCD Usage: Issuer Authentication Data" "17.")
    (140 "Generic EMV Transport Usage: Issuer Authentication Data" "17.")
    (142 "Issuer Script" "256.")
    (143 "Issuer Script Results" "21.")
    (144 "Cryptogram Transaction Type" "1")
    (145 "Terminal Country Code" "2")
    (146 "Terminal Transaction Date" "3")
    (147 "Cryptogram Amount" "6")
    (148 "Cryptogram Currency Code" "2")
    (149 "Cryptogram Cashback Amount" "6")
    (152 "Secondary PIN Block" "8")
    ;; (127 "File Maintenance" "256.")
    (127 "Inquiry Control Data" "256.")))


(provide 'hpns-alists)
