;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-babel-insert-hyphen
	LaTeX-insert-item
	LaTeX-insert-left-brace
	TeX-insert-dollar
	TeX-insert-quote
	TeX-insert-sub-or-superscript
	beginning-of-visual-line
	c-electric-pound
	c-electric-semi&comma
	c-electric-star
	c-indent-line-or-region
	comment-line
	electric-newline-and-maybe-indent
	end-of-buffer
	end-of-visual-line
	indent-for-tab-command
	indent-new-comment-line
	kill-region
	kill-sentence
	kill-visual-line
	mark-sexp
	move-lines-up
	org-end-of-line
	org-meta-return
	org-return
	org-self-insert-command
	org-shiftcontrolright
	org-shiftright
	org-yank
	overwrite-mode
	reindent-then-newline-and-indent
	sh-assignment
	ts-electric-brace
	typescript-insert-and-autoconvert-to-template
	typescript-insert-and-indent
	))

(setq mc/cmds-to-run-once
      '(
	LaTeX-close-environment
	LaTeX-environment
	TeX-insert-backslash
	completion-at-point
	elfeed-search-update--force
	forward-sentence
	handle-switch-frame
	mouse-drag-secondary
	my-next-buffer
	my-previous-buffer
	save-buffers-kill-terminal
	visual-line-mode
	))
